data_root: ./data

launcher:
  apps:
    - name: Paint
      icon_path: assets/icons/paint/paint_512.png
      command: "python -m toddlerbox.paint"
    - name: Photos
      icon_path: assets/icons/photos/photos_512.png
      command: "python -m toddlerbox.photos"
    - name: Typing
      icon_path: assets/icons/typing/typing_512.png
      command: "python -m toddlerbox.typing"

paint:
  autosave_seconds: 10
  max_archives: 100
  palette:
    - [0, 0, 0]
    - [255, 255, 255]
    - [220, 20, 60]
    - [255, 127, 0]
    - [255, 215, 0]
    - [34, 139, 34]
    - [65, 105, 225]
    - [138, 43, 226]
    - [255, 105, 180]
    - [210, 105, 30]
    - [105, 105, 105]
    - [0, 191, 255]
    - [154, 205, 50]

photos:
  thumb_batch: 1
  thumb_idle_ms: 120
  thumb_scroll_idle_ms: 120
  thumb_time_budget_ms: 5
